# Starter Kit nginx configuration
# Ref: https://github.com/kubernetes/ingress-nginx/tree/helm-chart-4.0.6/charts/ingress-nginx
# See Also: https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/03-setup-ingress-controller/guides/nginx_performance_considerations.md

controller:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  service:
    type: LoadBalancer
    annotations:
      # Enable proxy protocol
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: true
      service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"

  # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
  config:
    use-proxy-protocol: "true"
    keep-alive-requests: "10000"
    upstream-keepalive-requests: "1000"
    worker-processes: "auto"
    max-worker-connections: "65535"
    use-gzip: "true"
