---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hsl-api
    namespace: backend
  spec:

    replicas: 1

    selector:
      matchLabels:
        app: hsl-api
    strategy:

      type: RollingUpdate

    template:
      metadata:
        labels:
          app: hsl-api
      spec:
        containers:
          - name: hsl-api
            image: registry.digitalocean.com/dmw2151-internal/hsl
            ports: 
              - name: http
                containerPort: 2151
            env:
              - name: REDIS_HOST
                value: "redis.redis"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_DB
                value: "0"
              - name: REDISCLI_AUTH
                valueFrom:
                  secretKeyRef:
                    name: redisauth
                    key: redisclientauth
            resources:
              requests:
                cpu: 100m
                memory: 50Mi
              limits:
                cpu: 200m
                memory: 100Mi