---
  apiVersion: v1
  kind: Service
  metadata:
    name: hsl-api
    namespace: backend
  spec:
    ports:
      - name: http
        port: 80
        targetPort: 2151
    selector:
      app: hsl-api